"""This module contains constants used throughout the application."""
APP_BASE_URL = "http://localhost:8080"
OAUTH_BASE_URL = "https://oauth.ccbchurch.com"
API_BASE_URL = "https://api.ccbchurch.com"
DB_FILENAME = "db.json"
