/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.churchcommunitybuilder;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertThrows;

class AppTest {

    @Test
    void constructorHttpRequestFactoryMustNotBeNull() {
        assertThrows(
                NullPointerException.class,
                () -> {
                    new RestClient(null);
                }
        );
    }

}
